-- Khodroyab vehicle catalog batch 01: user-provided brands/models/trims.
-- Canonicalized Persian spelling and mapped model -> trim hierarchy.
BEGIN;

UPDATE public.vehicle_brands SET name_fa='ام وی ام', name_en='MVM', slug='mvm', normalized_name='ام وی ام' WHERE normalized_name='mvm';

INSERT INTO public.vehicle_brands (name_fa,name_en,slug,normalized_name,is_active,sort_order)
VALUES
('آئودی','Audi','audi','آئودی',true,10),('آریسان','Arisan','arisan','آریسان',true,20),('آریو','Ario','ario','آریو',true,30),('آلفارومئو','Alfa Romeo','alfa-romeo','آلفارومئو',true,40),('آمیکو وانت','Amico','amico','آمیکو وانت',true,50),('اپل','Opel','opel','اپل',true,60),('اس دبلیو ام','SWM','swm','اس دبلیو ام',true,70),('ام جی','MG','mg','ام جی',true,80),('ام وی ام','MVM','mvm','ام وی ام',true,90),('ایران خودرو','Iran Khodro','iran-khodro','ایران خودرو',true,100),('ایسوزو','Isuzu','isuzu','ایسوزو',true,110),('اکستریم','Exeed','exeed','اکستریم',true,120)
ON CONFLICT (normalized_name) DO UPDATE SET name_fa=EXCLUDED.name_fa,name_en=EXCLUDED.name_en,slug=EXCLUDED.slug,is_active=true,sort_order=EXCLUDED.sort_order;

INSERT INTO public.vehicle_models (brand_id,name_fa,name_en,slug,normalized_name,is_active,sort_order)
SELECT b.id,v.name_fa,v.name_en,v.slug,v.normalized_name,true,v.sort_order
FROM public.vehicle_brands b
JOIN (VALUES
('آئودی','Q4 e-tron','Q4 e-tron','q4-e-tron','q4 e-tron',10),('آئودی','Q5 e-tron','Q5 e-tron','q5-e-tron','q5 e-tron',20),('آئودی','A3 Sedan','A3 Sedan','a3-sedan','a3 sedan',30),('آئودی','A4','A4','a4','a4',40),('آئودی','Q5','Q5','q5','q5',50),('آئودی','TT','TT','tt','tt',60),
('آریسان','وانت آریسان','Arisan Pickup','arisan-pickup','وانت آریسان',10),('آریسان','وانت آریسان 2','Arisan 2 Pickup','arisan-2-pickup','وانت آریسان 2',20),('آریو','آریو','Ario','ario','آریو',10),('آلفارومئو','4C','4C','4c','4c',10),('آلفارومئو','جولیتا','Giulietta','giulietta','جولیتا',20),('آلفارومئو','میتو','MiTo','mito','میتو',30),
('آمیکو وانت','وانت آمیکو آراز','Amico Araz Pickup','amico-araz-pickup','وانت آمیکو آراز',10),('آمیکو وانت','وانت آمیکو آسنا','Amico Asena Pickup','amico-asena-pickup','وانت آمیکو آسنا',20),
('اپل','آسترا','Astra','astra','آسترا',10),('اپل','امگا','Omega','omega','امگا',20),('اپل','اینسیگنیا','Insignia','insignia','اینسیگنیا',30),('اپل','کالیبرا','Calibra','calibra','کالیبرا',40),('اپل','کراس‌لند','Crossland','crossland','کراس لند',50),('اپل','کورسا','Corsa','corsa','کورسا',60),('اپل','موکا','Mokka','mokka','موکا',70),
('اس دبلیو ام','G01','G01','g01','g01',10),('اس دبلیو ام','G01F','G01F','g01f','g01f',20),
('ام جی','ام جی 3','MG 3','mg-3','ام جی 3',10),('ام جی','ام جی 350','MG 350','mg-350','ام جی 350',20),('ام جی','ام جی 360','MG 360','mg-360','ام جی 360',30),('ام جی','ام جی 4 EV','MG4 EV','mg4-ev','ام جی 4 ev',40),('ام جی','ام جی 5','MG 5','mg-5','ام جی 5',50),('ام جی','ام جی 550','MG 550','mg-550','ام جی 550',60),('ام جی','ام جی 6','MG 6','mg-6','ام جی 6',70),('ام جی','ام جی 7','MG 7','mg-7','ام جی 7',80),('ام جی','ام جی تورس','MG Torus','mg-torus','ام جی تورس',90),('ام جی','ام جی رووی D7','MG Roewe D7','mg-roewe-d7','ام جی رووی d7',100),('ام جی','ام جی GS','MG GS','mg-gs','ام جی gs',110),('ام جی','ام جی GT','MG GT','mg-gt','ام جی gt',120),('ام جی','ام جی RX5','MG RX5','mg-rx5','ام جی rx5',130),
('ام وی ام','آریزو 5','Arrizo 5','arrizo-5','آریزو 5',10),('ام وی ام','M5 Pro','M5 Pro','m5-pro','m5 pro',20),('ام وی ام','X77','X77','x77','x77',30),('ام وی ام','110','110','110','110',40),('ام وی ام','110S','110S','110s','110s',50),('ام وی ام','315 صندوق‌دار','315 Sedan','315-sedan','315 صندوق دار',60),('ام وی ام','315 هاچ‌بک','315 Hatchback','315-hatchback','315 هاچ بک',70),('ام وی ام','315 هاچ‌بک پلاس','315 Hatchback Plus','315-hatchback-plus','315 هاچ بک پلاس',80),('ام وی ام','530','530','530','530',90),('ام وی ام','550','550','550','550',100),('ام وی ام','X22','X22','x22','x22',110),('ام وی ام','X22 Pro','X22 Pro','x22-pro','x22 pro',120),('ام وی ام','X33','X33','x33','x33',130),('ام وی ام','X33 Cross','X33 Cross','x33-cross','x33 cross',140),('ام وی ام','X33 S','X33 S','x33-s','x33 s',150),('ام وی ام','X55','X55','x55','x55',160),('ام وی ام','X55 Pro','X55 Pro','x55-pro','x55 pro',170),
('ایران خودرو','ری‌را','Rira','rira','ری را',10),('ایران خودرو','لونا GRE','Luna GRE','luna-gre','لونا gre',20),('ایسوزو','D-Max','D-Max','d-max','d-max',10),('اکستریم','LX','LX','lx','lx',10),('اکستریم','TXL','TXL','txl','txl',20),('اکستریم','VX','VX','vx','vx',30)
) AS v(brand_fa,name_fa,name_en,slug,normalized_name,sort_order)
ON v.brand_fa=b.name_fa
ON CONFLICT (brand_id,slug) DO UPDATE SET name_fa=EXCLUDED.name_fa,name_en=EXCLUDED.name_en,normalized_name=EXCLUDED.normalized_name,is_active=true,sort_order=EXCLUDED.sort_order;

INSERT INTO public.vehicle_trims (model_id,name_fa,name_en,slug,normalized_name,is_active,sort_order)
SELECT m.id,v.name_fa,v.name_en,v.slug,v.normalized_name,true,v.sort_order
FROM public.vehicle_models m
JOIN public.vehicle_brands b ON b.id=m.brand_id
JOIN (VALUES
('آئودی','Q4 e-tron','40','40','40','40',10),('آئودی','Q5 e-tron','40','40','40','40',10),('آئودی','A3 Sedan','1.5 لیتر توربو','1.5L Turbo','1-5l-turbo','1.5 لیتر توربو',10),('آئودی','A4','2.0 لیتر توربو','2.0L Turbo','2-0l-turbo','2.0 لیتر توربو',10),('آئودی','TT','رودستر','Roadster','roadster','رودستر',10),('آئودی','TT','کوپه','Coupe','coupe','کوپه',20),
('آریسان','وانت آریسان','بنزینی','Petrol','petrol','بنزینی',10),('آریسان','وانت آریسان','دوگانه‌سوز','Dual Fuel','dual-fuel','دوگانه سوز',20),('آریسان','وانت آریسان 2','دوگانه‌سوز','Dual Fuel','dual-fuel','دوگانه سوز',10),('آریو','آریو','اتوماتیک 1600cc','Automatic 1600cc','automatic-1600cc','اتوماتیک 1600cc',10),('آریو','آریو','دنده‌ای 1500cc','Manual 1500cc','manual-1500cc','دنده ای 1500cc',20),
('آمیکو وانت','وانت آمیکو آراز','تک‌دیفرانسیل','2WD','2wd','تک دیفرانسیل',10),('آمیکو وانت','وانت آمیکو آراز','دو‌دیفرانسیل','4WD','4wd','دو دیفرانسیل',20),('آمیکو وانت','وانت آمیکو آسنا','M244','M244','m244','m244',10),('آمیکو وانت','وانت آمیکو آسنا','بنزینی','Petrol','petrol','بنزینی',20),('آمیکو وانت','وانت آمیکو آسنا','دوگانه‌سوز','Dual Fuel','dual-fuel','دوگانه سوز',30),
('اپل','آسترا','سدان','Sedan','sedan','سدان',10),('اپل','آسترا','استیشن','Station Wagon','station-wagon','استیشن',20),('اپل','آسترا','سدان جدید','New Sedan','new-sedan','سدان جدید',30),('اپل','آسترا','سدان قدیم','Old Sedan','old-sedan','سدان قدیم',40),('اپل','آسترا','هاچ‌بک','Hatchback','hatchback','هاچ بک',50),('اپل','آسترا','هیبرید','Hybrid','hybrid','هیبرید',60),('اپل','آسترا','هاچ‌بک 1400cc','Hatchback 1400cc','hatchback-1400cc','هاچ بک 1400cc',70),('اپل','آسترا','هاچ‌بک 1600cc','Hatchback 1600cc','hatchback-1600cc','هاچ بک 1600cc',80),('اپل','موکا','1.2 لیتر توربو','1.2L Turbo','1-2l-turbo','1.2 لیتر توربو',10),
('ام جی','ام جی 360','اتوماتیک','Automatic','automatic','اتوماتیک',10),('ام جی','ام جی 360','اتوماتیک توربو','Automatic Turbo','automatic-turbo','اتوماتیک توربو',20),('ام جی','ام جی 360','دنده‌ای','Manual','manual','دنده ای',30),('ام جی','ام جی 4 EV','XPower','XPower','xpower','xpower',10),('ام جی','ام جی 6','Magnette','Magnette','magnette','magnette',10),('ام جی','ام جی 6','New','New','new','new',20),('ام جی','ام جی 6','GT','GT','gt','gt',30),
('ام وی ام','آریزو 5','EV','EV','ev','ev',10),('ام وی ام','آریزو 5','Sport FL','Sport FL','sport-fl','sport fl',20),('ام وی ام','M5 Pro','1.5 لیتر توربو','1.5L Turbo','1-5l-turbo','1.5 لیتر توربو',10),('ام وی ام','X77','1.5 لیتر توربو الیت','1.5L Turbo Elite','1-5l-turbo-elite','1.5 لیتر توربو الیت',10),('ام وی ام','110','اتوماتیک 2 سیلندر','Automatic 2-Cylinder','automatic-2-cylinder','اتوماتیک 2 سیلندر',10),('ام وی ام','110','اتوماتیک 4 سیلندر','Automatic 4-Cylinder','automatic-4-cylinder','اتوماتیک 4 سیلندر',20),('ام وی ام','110S','اسپرت لاکچری','Sport Luxury','sport-luxury','اسپرت لاکچری',10),('ام وی ام','110S','کامفورت','Comfort','comfort','کامفورت',20),('ام وی ام','110S','لاکچری','Luxury','luxury','لاکچری',30),('ام وی ام','315 صندوق‌دار','اسپرت لاکچری','Sport Luxury','sport-luxury','اسپرت لاکچری',10),('ام وی ام','315 صندوق‌دار','ساده','Standard','standard','ساده',20),('ام وی ام','315 هاچ‌بک','اسپرت اکسلنت','Sport Excellent','sport-excellent','اسپرت اکسلنت',10),('ام وی ام','315 هاچ‌بک','اسپرت لاکچری','Sport Luxury','sport-luxury','اسپرت لاکچری',20),('ام وی ام','315 هاچ‌بک','ساده','Standard','standard','ساده',30),('ام وی ام','550','اتوماتیک','Automatic','automatic','اتوماتیک',10),('ام وی ام','550','دنده‌ای','Manual','manual','دنده ای',20),('ام وی ام','X22','اتوماتیک اسپرت','Automatic Sport','automatic-sport','اتوماتیک اسپرت',10),('ام وی ام','X22','اتوماتیک اکسلنت','Automatic Excellent','automatic-excellent','اتوماتیک اکسلنت',20),('ام وی ام','X22','اتوماتیک لاکچری','Automatic Luxury','automatic-luxury','اتوماتیک لاکچری',30),('ام وی ام','X22','اتوماتیک ساده','Automatic Standard','automatic-standard','اتوماتیک ساده',40),('ام وی ام','X22','دنده‌ای لاکچری','Manual Luxury','manual-luxury','دنده ای لاکچری',50),('ام وی ام','X22','دنده‌ای ساده','Manual Standard','manual-standard','دنده ای ساده',60),('ام وی ام','X22 Pro','MT','MT','mt','mt',10),('ام وی ام','X22 Pro','اکسلنت','Excellent','excellent','اکسلنت',20),('ام وی ام','X22 Pro','IE','IE','ie','ie',30),('ام وی ام','X33','اتوماتیک','Automatic','automatic','اتوماتیک',10),('ام وی ام','X33','دنده‌ای','Manual','manual','دنده ای',20),('ام وی ام','X33 Cross','اتوماتیک','Automatic','automatic','اتوماتیک',10),('ام وی ام','X33 Cross','دستی','Manual','manual','دستی',20),('ام وی ام','X33 S','اسپرت','Sport','sport','اسپرت',10),('ام وی ام','X33 S','ساده','Standard','standard','ساده',20),('ام وی ام','X33 S','نیو فیس','New Face','new-face','نیو فیس',30),('ام وی ام','X55','اکسلنت','Excellent','excellent','اکسلنت',10),('ام وی ام','X55','اکسلنت اسپرت','Excellent Sport','excellent-sport','اکسلنت اسپرت',20),('ام وی ام','X55 Pro','Li','Li','li','li',10),('ام وی ام','X55 Pro','اکسلنت','Excellent','excellent','اکسلنت',20),('ام وی ام','X55 Pro','اکسلنت اسپرت','Excellent Sport','excellent-sport','اکسلنت اسپرت',30),('ام وی ام','X55 Pro','IE','IE','ie','ie',40),('ام وی ام','X55 Pro','IE اسپرت','IE Sport','ie-sport','ie اسپرت',50),
('ایران خودرو','ری‌را','1.7 لیتر توربو بنزینی','1.7L Turbo Petrol','1-7l-turbo-petrol','1.7 لیتر توربو بنزینی',10),('ایران خودرو','ری‌را','برقی','Electric','electric','برقی',20),('ایران خودرو','لونا GRE','برقی','Electric','electric','برقی',10),('ایسوزو','D-Max','دوکابین','Double Cab','double-cab','دوکابین',10)
) AS v(brand_fa,model_fa,name_fa,name_en,slug,normalized_name,sort_order)
ON v.brand_fa=b.name_fa AND v.model_fa=m.name_fa
ON CONFLICT (model_id,slug) DO UPDATE SET name_fa=EXCLUDED.name_fa,name_en=EXCLUDED.name_en,normalized_name=EXCLUDED.normalized_name,is_active=true,sort_order=EXCLUDED.sort_order;

COMMIT;
